<?php
session_start();
include 'db_connect.php'; // Include the connection file

$showNotificationScript = '';

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $email = $_POST["email"];
    $password = $_POST["password"];

    // Secure version using prepared statements (SQL injection protection)
    $stmt = $conn->prepare("SELECT * FROM users WHERE email = ?");
    $stmt->bind_param("s", $email);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows > 0) {
        $user = $result->fetch_assoc();

        // Verify the password using password_verify (if password is hashed)
        // if (password_verify($password, $user['password'])) {
        // Here there is manual password authentication(proving good coding practice.)
        if ($password === $user['password']){

            // Set session variables and redirect to the profile page
            $_SESSION["user_id"] = $user["id"];
            $_SESSION["username"] = $user["username"];
            header("Location: home.php");
            exit();
        } else {
            // Invalid password
            $showNotificationScript = "<script>
                    document.addEventListener('DOMContentLoaded', function() {
                        showNotification('Invalid password.', 'error');
                    });
                  </script>";
        }
    } else {
        // No account found with that email
        $showNotificationScript = "<script>
                document.addEventListener('DOMContentLoaded', function() {
                    showNotification('Wrong details, please try again!', 'error');
                });
              </script>";
    }

    $stmt->close();
}

$conn->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="register.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>Login</title>
</head>
<body>
    <div id="notification" class="notification"></div> <!-- Notification container -->
    
    <div class="header">
        <img src="assets/logo.png">
        <h2>MAAUN/21/CBS/0028</h2>
    </div>

    <div class="form-container">
        <i class="bi bi-shield-fill-check"></i>
        <h2 class="secure">Secured Login</h2>
        <form action="login_secure.php" method="POST">
            <label for="email">Email:</label>
            <input type="text" name="email" required>

            <label for="password">Password:</label>
            <input type="password" name="password" required>

            <button type="submit">Login</button>
        </form>
    </div>
    <script>
    function showNotification(message, type = 'success') {
        var notification = document.getElementById('notification');
        
        // Set the message and the notification type
        notification.innerHTML = message;
        notification.classList.add('show');
        
        // Apply error styling if type is 'error'
        if (type === 'error') {
            notification.classList.add('error');
        } else {
            notification.classList.remove('error');
        }
        
        // Hide the notification after 4 seconds
        setTimeout(function() {
            notification.classList.remove('show');
        }, 4000);
    }
    </script>

    <!-- Place the notification script generated by PHP -->
    <?php echo $showNotificationScript; ?>
</body>
</html>
